<template>
    <div>
        <img src="../assets/paris1.jpg" alt="" class="background" />

        <div style="z-index: 1000; position: relative; display: flex">
            <div style="padding-left: 200px">
                <div style="position: fixed">
                    <div
                        style="
                            font-size: 30px;
                            color: white;
                            padding-top: 5rem;
                            font-family: 'Segoe UI', Tahoma, Geneva, Verdana,
                                sans-serif;
                            text-transform: uppercase;
                            opacity: 90%;
                            letter-spacing: 10px;
                        "
                    >
                        information assurance and security
                    </div>
                    <hr
                        style="
                            width: 70rem;
                            margin-top: 50px;
                            border: 0.5px solid gray;
                            opacity: 30%;
                        "
                    />
                </div>

                <div
                    style="
                        font-size: 80px;
                        color: white;
                        margin-top: 20rem;
                        margin-left: 100px;
                        margin-bottom: 5rem;
                        letter-spacing: 10px;
                        text-transform: uppercase;
                    "
                >
                    Encryption
                </div>
                <v-text-field
                    label="MESSAGE"
                    dark
                    style="
                        width: 100%;
                        margin-left: 30px;
                        margin-bottom: 40px;
                        font-size: 30px;
                    "
                    v-model="encryptMes"
                ></v-text-field>

                <v-text-field
                    label="KEYWORD"
                    dark
                    style="
                        width: 100%;
                        margin-left: 30px;
                        margin-bottom: 40px;
                        font-size: 30px;
                    "
                    v-model="encryptKey"
                    v-on:keyup="encrypt(encryptMes, encryptKey)"
                ></v-text-field>

                <div style="width: 100%; font-size: 30px" class="container">
                    <div>
                        <img src="../assets/scroll.png" style="width: 110%" />
                    </div>
                    <div class="centered">{{ encryptCode }}</div>
                </div>

                <div
                    style="
                        font-size: 80px;
                        color: white;
                        margin-top: 20rem;
                        margin-left: 100px;
                        margin-bottom: 5rem;
                        letter-spacing: 10px;
                        text-transform: uppercase;
                    "
                >
                    Decryption
                </div>
                <v-text-field
                    label="CODE"
                    dark
                    style="
                        width: 100%;
                        margin-left: 30px;
                        margin-bottom: 40px;
                        font-size: 30px;
                    "
                    v-model="decryptCode"
                ></v-text-field>
                <v-text-field
                    label="KEYWORD"
                    dark
                    style="
                        width: 100%;
                        margin-left: 30px;
                        margin-bottom: 60px;
                        font-size: 30px;
                    "
                    v-model="decryptKey"
                    v-on:keyup="decrypt(decryptCode, decryptKey)"
                ></v-text-field>
                <div style="width: 100%; font-size: 30px" class="container">
                    <div>
                        <img src="../assets/scroll.png" style="width: 110%" />
                    </div>
                    <div class="centered">{{ decryptMes }}</div>
                </div>
            </div>

            <div
                style="
                    z-index: 1000;
                    position: relative;
                    display: flex;
                    width: 50%;
                "
            ></div>
            <div style="flex: 60%; margin-right: 80px">
                <div>
                    <img src="../assets/char.png" style="margin-bottom: 0px" />
                </div>
                <div><img src="../assets/char2.png" /></div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    data() {
        return {
            encryptMes: "",
            encryptKey: "",
            encryptCode: "",
            decryptCode: "",
            decryptKey: "",
            decryptMes: "",
        };
    },
    methods: {
        encrypt(encryptMes, encryptKey) {
            const list = [
                [
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                ],
                [
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                ],
                [
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                ],
                [
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                ],
                [
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                ],
                [
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                ],
                [
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                ],
                [
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                ],
                [
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                ],
                [
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                ],
                [
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                ],
                [
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                ],
                [
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                ],
                [
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                ],
                [
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                ],
                [
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                ],
                [
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                ],
                [
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                ],
                [
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                ],
                [
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                ],
                [
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                ],
                [
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                ],
                [
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                ],
                [
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                ],
                [
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                ],
                [
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                ],
            ];
            console.log("Encrypt message:" + encryptMes);
            console.log("Encrypt key:" + encryptKey);
            let newkey = "";
            let newtext = "";

            //create keyword in reverse
            if (
                encryptKey.replaceAll(/\s/g, "") == "" ||
                encryptMes.replaceAll(/\s/g, "") == ""
            ) {
                return "";
            }
            for (
                let i =
                    encryptKey.toLowerCase().replaceAll(/\s/g, "").length - 1;
                i >= 0;
                i--
            ) {
                newkey += encryptKey.toLowerCase().replaceAll(/\s/g, "")[i];
            }

            //create new text
            let counter = 0;
            let coordinates = "";
            for (
                let i = 0;
                i < encryptMes.toLowerCase().replaceAll(/\s/g, "").length;
                i++
            ) {
                if (counter > newkey.length - 1) {
                    counter = 0;
                }
                newtext += newkey[counter];
                counter += 1;
            }
            for (let i = 0; i < newtext.length; i++) {
                for (let j = 0; j < list[0].length; j++) {
                    if (
                        encryptMes.toLowerCase().replaceAll(/\s/g, "")[i] ===
                        list[j][0]
                    ) {
                        coordinates += j + ",";
                    }
                }
                for (let k = 0; k < list[0].length; k++) {
                    if (newtext[i] === list[k][0]) {
                        coordinates += k + "\n";
                    }
                }
            }

            let arr = coordinates
                .substring(0, coordinates.length - 1)
                .split("\n");
            let encryptcode = "";
            for (let i = 0; i < arr.length; i++) {
                let a = arr[i].split(",");
                encryptcode += list[a[0]][a[1]];
            }
            this.encryptCode = encryptcode.replace(/(.{5})/g, "$1 ");
        },
        decrypt(decryptCode, decryptKey) {
            console.log(decryptCode);
            console.log(decryptKey);
            const list = [
                [
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                ],
                [
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                ],
                [
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                ],
                [
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                ],
                [
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                ],
                [
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                ],
                [
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                ],
                [
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                ],
                [
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                ],
                [
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                ],
                [
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                ],
                [
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                ],
                [
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                ],
                [
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                ],
                [
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                ],
                [
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                ],
                [
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                ],
                [
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                ],
                [
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                ],
                [
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                ],
                [
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                ],
                [
                    "v",
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                ],
                [
                    "w",
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                ],
                [
                    "x",
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                ],
                [
                    "y",
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                ],
                [
                    "z",
                    "a",
                    "b",
                    "c",
                    "d",
                    "e",
                    "f",
                    "g",
                    "h",
                    "i",
                    "j",
                    "k",
                    "l",
                    "m",
                    "n",
                    "o",
                    "p",
                    "q",
                    "r",
                    "s",
                    "t",
                    "u",
                    "v",
                    "w",
                    "x",
                    "y",
                ],
            ];

            //create new text
            let counter = 0;
            let coordinates = "";
            let newtext = "";
            let newkey = "";
            //create keyword in reverse

            for (
                let i =
                    decryptKey.toLowerCase().replaceAll(/\s/g, "").length - 1;
                i >= 0;
                i--
            ) {
                newkey += decryptKey.toLowerCase().replaceAll(/\s/g, "")[i];
            }

            console.log(newkey);

            for (
                let i = 0;
                i <
                decryptCode
                    .toLowerCase()
                    .replaceAll(/\s/g, "")
                    .toLowerCase()
                    .replaceAll(/\s/g, "").length;
                i++
            ) {
                if (counter > newkey.length - 1) {
                    counter = 0;
                }
                newtext += newkey[counter];
                counter += 1;
            }
            console.log("newtext" + newtext);
            console.log("newkey" + newkey);
            for (let i = 0; i < newtext.length; i++) {
                for (let j = 0; j < list[0].length; j++) {
                    if (newtext[i] == list[0][j]) {
                        for (let k = 0; k < list[0].length; k++) {
                            if (
                                decryptCode.toLowerCase().replaceAll(/\s/g, "")[
                                    i
                                ] == list[k][j]
                            ) {
                                coordinates += list[0][k];
                            }
                        }
                    }
                }
            }
            this.decryptMes = coordinates.replace(/(.{5})/g, "$1 ");
        },
    },
};
</script>

<style scoped>
.background {
    position: fixed;
    object-fit: cover;
    width: 100%;
    height: 100%;
}

.container {
    position: relative;
    text-align: center;
    color: black;
}
.centered {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    text-transform: uppercase;
}
</style>
